# Generated by Django 5.2.4 on 2025-09-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
