# Generated by Django 5.2.4 on 2025-09-08 19:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_server_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='u_uniqueid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
