# Generated by Django 5.2.4 on 2025-09-08 19:47

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    server_model = apps.get_model("server", "Server")
    for row in server_model.objects.all():
        row.u_uniqueid = uuid.uuid4()
        row.save(update_fields=["u_uniqueid"])

class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_server_u_uniqueid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]

