# Generated by Django 5.2.4 on 2025-09-08 19:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20250908_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='u_uniqueid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False),
        ),
    ]
